[package]
name = "rust-nes"
version = "0.1.0"
authors = ["Kieran <kraine93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
lazy_static = "1.4.0"
sdl2 = "0.34.5"
